version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/install_dependencies
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: ubuntu
